# Generated by Django 5.0.14 on 2026-02-18 20:42

import django.db.models.deletion
import leads.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_primary', models.CharField(max_length=15, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
                ('producto_interes', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_completa', models.CharField(blank=True, max_length=255)),
                ('estatus', models.CharField(default='PROSPECTO', max_length=20)),
                ('calificacion', models.IntegerField(default=0)),
                ('plan', models.CharField(default='SEGUIMIENTO', max_length=50)),
                ('notas_variadas', models.JSONField(default=leads.models.default_notas_variadas)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_en_zona', to='users.catubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=200)),
                ('regimen_fiscal', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_fiscal', to='leads.corelead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conflicto', models.CharField(choices=[('DUPLICADO_IMPORT', 'Duplicado en Importación'), ('RECLAMO_MANUAL', 'Reclamo Manual de Propiedad')], max_length=30)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTO', 'Resuelto'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Quien reclama')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos', to='leads.corelead')),
            ],
        ),
    ]
