# Generated by Django 5.0.14 on 2026-02-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadDispute',
        ),
    ]
