# Generated by Django 5.0.14 on 2026-02-22 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_delete_leaddispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corelead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
