# Generated by Django 5.0.14 on 2026-02-23 05:25

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_corelead_created_at_corelead_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelead',
            name='estatus',
            field=django_fsm.FSMField(default='PROSPECTO', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='corelead',
            name='phone_primary',
            field=models.CharField(max_length=15),
        ),
    ]
