# Generated by Django 5.0.14 on 2026-02-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_corelead_estatus_alter_corelead_phone_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelead',
            name='next_action_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Próximo Contacto'),
        ),
    ]
