# Generated by Django 5.0.14 on 2026-02-28 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_notificacion'),
        ('users', '0002_catespecialidad_catproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelead',
            name='especialidad_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.catespecialidad'),
        ),
        migrations.AddField(
            model_name='corelead',
            name='producto_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.catproducto'),
        ),
    ]
