# Generated by Django 5.0.14 on 2026-03-01 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_corelead_especialidad_cat_corelead_producto_cat'),
        ('users', '0003_catproducto_familia_alter_catproducto_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaTransaccional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_extra', to='leads.corelead')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_transaccionales', to='users.catproducto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta Transaccional',
                'verbose_name_plural': 'Ventas Transaccionales',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
