# Generated by Django 5.0.14 on 2026-03-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_ventatransaccional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatransaccional',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', '🟡 Pendiente (Por contactar)'), ('EN_GESTION', '🔵 En Gestión (Contactado / Negociando)'), ('CONCRETADO', '🟢 Concretado (Ganado / Pagado)'), ('DESCARTADO', '🔴 Descartado (Perdido / No le interesa)')], default='PENDIENTE', max_length=20),
        ),
    ]
