# Generated by Django 5.0.14 on 2026-03-02 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_ventatransaccional_estatus'),
        ('users', '0003_catproducto_familia_alter_catproducto_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productos_objetivo', models.ManyToManyField(blank=True, to='users.catproducto')),
                ('vendedores_asignados', models.ManyToManyField(blank=True, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento / Campaña',
                'verbose_name_plural': 'Eventos y Campañas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
