# Generated by Django 5.0.14 on 2026-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='productos_objetivo',
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('EXPO', 'Expo / Congreso'), ('TALLER', 'Taller / Capacitación')], default='EXPO', max_length=20),
        ),
    ]
