# Generated by Django 5.0.14 on 2026-03-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_remove_evento_productos_objetivo_evento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estados_objetivo',
            field=models.JSONField(default=list, help_text='Lista de nombres de estados'),
        ),
        migrations.AddField(
            model_name='evento',
            name='linea_producto',
            field=models.CharField(choices=[('SPORT', 'Línea Sport'), ('PET', 'Línea Pet'), ('DENTAL', 'Línea Dental'), ('PODOLOGICO', 'Línea Podológica'), ('BEAUTY', 'Línea Beauty'), ('TODAS', 'Todas las Líneas')], default='TODAS', max_length=20),
        ),
    ]
