# Generated by Django 5.0.14 on 2026-03-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_evento_estados_objetivo_evento_linea_producto'),
        ('users', '0004_cattitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelead',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corelead',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corelead',
            name='nombre_pila',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corelead',
            name='titulo_cortesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.cattitulo'),
        ),
    ]
