# Generated by Django 5.0.14 on 2026-03-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_corelead_apellido_materno_corelead_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono_master', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clínica / Grupo',
                'verbose_name_plural': 'Clínicas y Grupos Corporativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='corelead',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='leads.clinica'),
        ),
    ]
