# Generated by Django 5.0.14 on 2026-03-14 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_clinica_corelead_clinica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datos_crudos', models.JSONField(default=dict)),
                ('datos_parseados', models.JSONField(default=dict)),
                ('motivo_conflicto', models.TextField()),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('RESUELTO', 'Resuelto / Inyectado'), ('DESCARTADO', 'Descartado / Basura')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_staging', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead en Cuarentena',
                'verbose_name_plural': 'Leads en Cuarentena',
                'ordering': ['created_at'],
            },
        ),
    ]
