# Generated by Django 5.0.14 on 2026-03-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_leadstaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('estancamiento', 'Lead Estancado (> 30 días)'), ('reactivacion', 'Reactivación Programada'), ('no_cierre', 'Revisión de No Cierre'), ('fidelizacion', 'Seguimiento Post-Venta'), ('capacitacion', 'Capacitación Post-Venta (8 días)'), ('calidad', 'Llamada de Calidad (180 días)'), ('mantenimiento', 'Mantenimiento Preventivo (18 meses)'), ('general', 'Aviso General')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrackingPostVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitacion_dada', models.BooleanField(default=False)),
                ('fecha_capacitacion', models.DateTimeField(blank=True, null=True)),
                ('calidad_hecha', models.BooleanField(default=False)),
                ('fecha_calidad', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_postventa', to='leads.corelead')),
            ],
            options={
                'verbose_name': 'Tracking Post-Venta',
                'verbose_name_plural': 'Tracking Post-Venta',
            },
        ),
    ]
