# Generated by Django 5.0.14 on 2026-03-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_notificacion_tipo_trackingpostventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corelead',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='corelead',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='corelead',
            name='producto_interes',
        ),
    ]
