# Generated by Django 5.0.14 on 2026-03-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_remove_corelead_especialidad_remove_corelead_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelead',
            name='es_historico',
            field=models.BooleanField(default=False),
        ),
    ]
