# Generated by Django 5.0.14 on 2026-03-25 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_corelead_es_historico'),
        ('users', '0004_cattitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas', to='users.catubicacion'),
        ),
    ]
