# Generated by Django 5.0.14 on 2026-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_clinica_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstaging',
            name='origen',
            field=models.CharField(choices=[('HISTORICO', 'Histórico / Dirección'), ('AGENTE', 'Operación Diaria Agentes')], default='HISTORICO', max_length=20),
        ),
    ]
