# Generated by Django 5.0.14 on 2026-04-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_leadstaging_origen'),
        ('users', '0005_catlada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ciudades_objetivo',
            field=models.ManyToManyField(blank=True, related_name='eventos_asociados', to='users.catubicacion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estados_objetivo',
            field=models.JSONField(default=list, help_text='[DEPRECADO] Lista de nombres de estados'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('EXPO', 'Expo / Congreso'), ('TALLER', 'Taller / Capacitación'), ('CAMPAÑA', 'Campaña Digital / Marketing')], default='EXPO', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, help_text='Notas sobre la participación del cliente', null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_vinculados', to='leads.evento')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asociados', to='leads.corelead')),
            ],
            options={
                'verbose_name': 'Cliente en Evento/Campaña',
                'verbose_name_plural': 'Clientes en Eventos/Campañas',
                'unique_together': {('evento', 'lead')},
            },
        ),
    ]
