# Generated by Django 5.0.14 on 2026-04-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_evento_ciudades_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='linea_producto',
            field=models.CharField(choices=[('SPORT', 'Línea Sport'), ('PET', 'Línea Pet'), ('DENTAL', 'Línea Dental'), ('PODOLOGICO', 'Línea Podológica'), ('BEAUTY', 'Línea Beauty'), ('SERVICIO', 'Servicios'), ('ACCESORIO', 'Accesorios'), ('TODAS', 'Todas las Líneas')], default='TODAS', max_length=20),
        ),
    ]
