# Generated by Django 5.0.14 on 2026-06-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_evento_linea_producto'),
        ('users', '0005_catlada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='ExcepcionEspecialidadLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_producto', models.CharField(choices=[('SPORT', 'Línea Sport'), ('PET', 'Línea Pet'), ('DENTAL', 'Línea Dental'), ('PODOLOGICO', 'Línea Podológica'), ('BEAUTY', 'Línea Beauty'), ('SERVICIO', 'Servicios'), ('ACCESORIO', 'Accesorios'), ('TODAS', 'Todas las Líneas')], max_length=20)),
                ('permitido', models.BooleanField(default=True, help_text='True para permitir la participación, False para bloquearla (incluso si por defecto estuviera permitida).')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_linea', to='users.catespecialidad')),
            ],
            options={
                'verbose_name': 'Excepción de Especialidad por Línea',
                'verbose_name_plural': 'Excepciones de Especialidad por Línea',
                'unique_together': {('especialidad', 'linea_producto')},
            },
        ),
    ]
