# Generated by Hand on 2026-07-16

from django.db import migrations
from django.utils import timezone


def create_alerts_schedule(apps, schema_editor):
    try:
        # Intentamos obtener el modelo Schedule de django_q
        Schedule = apps.get_model('django_q', 'Schedule')
    except LookupError:
        # Si no está instalado django_q en las apps, omitimos
        return

    # Registrar o actualizar la tarea programada
    # Usará schedule_type='C' (CRON) para ejecutarse en horarios seguros de oficina
    # (9:00 AM, 1:00 PM, 6:00 PM) para evitar la desconexión del servidor por la noche.
    Schedule.objects.update_or_create(
        name='Generación automática de alertas',
        defaults={
            'func': 'leads.tasks.ejecutar_generar_alertas',
            'schedule_type': 'C',  # Planificador por CRON
            'cron': '0 9,13,18 * * *',  # Horarios: 9:00 AM, 1:00 PM, 6:00 PM
            'repeats': -1,  # Repetir indefinidamente
            'next_run': timezone.now(),  # Iniciar de inmediato al levantar
        }
    )


def remove_alerts_schedule(apps, schema_editor):
    try:
        Schedule = apps.get_model('django_q', 'Schedule')
        Schedule.objects.filter(name='Generación automática de alertas').delete()
    except LookupError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_evento_estatus_excepcionespecialidadlinea'),
        ('django_q', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_alerts_schedule, reverse_code=remove_alerts_schedule),
    ]
