# Generated by Django 5.0.14 on 2026-07-25 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_setup_alerts_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatransaccional',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_asociadas', to='leads.evento'),
        ),
    ]
