# Generated by Django 5.0.14 on 2026-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('alias', models.TextField(blank=True, help_text='Sinónimos separados por coma. Ej: vet, veterinaria, animales', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Catálogo de Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('alias', models.TextField(blank=True, help_text='Sinónimos separados por coma. Ej: laser sport, laser ir sport', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Catálogo de Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
