# Generated by Django 5.0.14 on 2026-03-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_catespecialidad_catproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='catproducto',
            name='familia',
            field=models.CharField(choices=[('EQUIPO', 'Equipo Principal (Core Business)'), ('ACCESORIO', 'Accesorio / Consumible (Cross-selling)'), ('SERVICIO', 'Servicio Técnico / Mantenimiento'), ('EVENTO', 'Evento / Capacitación')], default='EQUIPO', help_text='Permite separar el modelo de negocio principal (FSM) de las ventas complementarias.', max_length=20),
        ),
        migrations.AlterField(
            model_name='catproducto',
            name='alias',
            field=models.TextField(blank=True, help_text='Sinónimos separados por coma. Ej: laser mini sport, laser ir sport', null=True),
        ),
    ]
