# Generated by Django 5.0.14 on 2026-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_catproducto_familia_alter_catproducto_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Dr., Dra., M.V.Z.', max_length=50, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Título de Cortesía',
                'verbose_name_plural': 'Catálogo de Títulos',
                'ordering': ['nombre'],
            },
        ),
    ]
