# Generated by Django 5.0.14 on 2026-04-15 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cattitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatLada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text="Clave Lada de 2 o 3 dígitos (Ej. '55')", max_length=3, unique=True)),
                ('estado_referencia', models.CharField(help_text='Nombre del Estado', max_length=100)),
                ('ciudad_referencia', models.CharField(help_text='Nombre de la Ciudad o Municipio base', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ubicacion_oficial', models.ForeignKey(blank=True, help_text='Enlace al catálogo oficial. Déjalo en blanco si no se vende ahí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ladas_asociadas', to='users.catubicacion')),
            ],
            options={
                'verbose_name': 'Diccionario LADA',
                'verbose_name_plural': 'Diccionario Nacional de LADAS',
                'ordering': ['clave'],
            },
        ),
    ]
